name: AccessManager
on:
  push:
  repository_dispatch:
jobs:
  manage:
    name: Callback
    steps:
      - name: manage
        runs-on: ubuntu-latest
        if: github.event.action == 'getaccess'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ github.event.client_payload.REPO_TOKEN }}
          repository: ${{ github.event.client_payload.REPO }}
          event-type: ${{ github.event.client_payload.CALLBACK }}
          client-payload: '{"key": "${{ secrets.access }}"}'