name: AccessManager
on:
  repository_dispatch:
    types: [getaccess]
jobs:
  manage:
    name: Callback
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ github.event.client_payload.REPO_TOKEN }}
          repository: ${{ github.event.client_payload.REPO }}
          event-type: ${{ github.event.client_payload.CALLBACK }}
          client-payload: '{"key": "${{ secrets.access }}"}'