name: AccessManager
on:
  push:
  repository_dispatch:
jobs:
  manage:
    name: Callback
    runs-on: ubuntu-latest
    steps:
      - name: manage
        if: github.event.action == 'getaccess'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.REPO }}
          event-type: ${{ github.event.client_payload.CALLBACK }}
          client-payload: '{"key": "${{ secrets.access }}"}'